/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#003642",
        "outline-variant": "#3c494e",
        "secondary-fixed-dim": "#edb1ff",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#f9d8ff",
        "on-secondary-fixed-variant": "#6e208c",
        "tertiary-fixed-dim": "#ffba3d",
        "on-tertiary-fixed-variant": "#604100",
        "tertiary-fixed": "#ffdeae",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary": "#432c00",
        "surface-container": "#201f1f",
        "surface": "#131313",
        "on-primary-container": "#00586b",
        "on-error": "#690005",
        "inverse-surface": "#e5e2e1",
        "surface-bright": "#3a3939",
        "on-secondary-fixed": "#320046",
        "on-tertiary-container": "#6c4900",
        "surface-variant": "#353534",
        "tertiary": "#ffd9a1",
        "on-primary-fixed-variant": "#004e5f",
        "surface-container-highest": "#353534",
        "primary-fixed": "#b4ebff",
        "inverse-primary": "#00677e",
        "secondary-container": "#6e208c",
        "secondary": "#edb1ff",
        "on-tertiary-fixed": "#281900",
        "primary-container": "#00d4ff",
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "outline": "#859398",
        "on-surface-variant": "#bbc9cf",
        "surface-tint": "#3cd7ff",
        "error": "#ffb4ab",
        "background": "#131313",
        "primary-fixed-dim": "#3cd7ff",
        "on-surface": "#e5e2e1",
        "on-secondary": "#520070",
        "on-primary-fixed": "#001f27",
        "primary": "#a8e8ff",
        "surface-dim": "#131313",
        "on-background": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "tertiary-container": "#feb528",
        "on-secondary-container": "#e498ff",
        "error-container": "#93000a"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "1rem", 
        lg: "2rem", 
        xl: "3rem", 
        full: "9999px"
      },
    },
  },
  plugins: [],
};